### ISSUE TITLE
Error querying the blockchain

### ISSUE THREAD

**Issue by troggy** [bitpay/bitcore-wallet-service#490]
All of my BWS instances (different versions) stopped working some time ago with similar errors:
````
WARN Insight https://insight.bitpay.com:443/api/addrs/txs?from=0&to=5 Returned Status: 403 
ERR! /v1/txhistory/?limit=5&r=28315 :500:Error querying the blockchain
````

I've checked the latest vanilla BWS from master and it doesn't work either. What can be the problem?

**Comment by matiu** [comment]
It could be that you IP was banned due to the number of request. Could you send it to me at matias@bitpay.com so I can check it? (and whitelist it). thanks and sorry about it.

**Comment by troggy** [comment]
Sent! I doubt it is because of the IP cause the issue was reported by my client and I didn't use BWS for awhile by myself.

**Comment by matiu** [comment]
closed offline. thanks.

**Comment by drvillo** [comment]
FWIW, I'm seeing this error while connecting BWS to my own instance of bitcore-node/Insight.

`WARN Insight http://localhost:3001/insight-api/api/addrs/txs?from=0&to=5 Returned Status: 404
ERR! /v1/txhistory/?limit=5&r=98364 :500:Error querying the blockchain
::ffff:192.168.1.33 2016-04-14T21:26:10.541Z "GET /bws/api/v1/txhistory/?limit=5&r=98364" 500 41 20.605 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36" <omitted>`

It looks this is because of how bws configuration is applied: Insight API listens to http://localhost:3001/insight-api/ but having a config.js like the following appends an extra "/api" to the request path, leading to a 404:

`  blockchainExplorerOpts: {
    livenet: {
      provider: 'insight',
      url: 'http://localhost:3001/insight-api',
     ...
`

**Comment by drvillo** [comment]
Update on my own comment in case someone else stumbles upon this as well. I just figured out config.js takes an optional apiPrefix attribute it its blockchain explorer element, which does what I need.
