### ISSUE TITLE
wallet address issue

### ISSUE THREAD

**Issue by flujodedinero** [bitpay/bitcore-wallet-service#645]
hello there, could you please help me to resolve this issue:

My wallet is not generating addresses enough, everytime it reaches 100BTC it starts repeating the last address.
How can I be sure my wallet is going to create unlimited and unique addresses?

Thanks for your answer

**Comment by isocolsky** [comment]
Copay allows a maximum of 20 consecutive new addresses. After this limit is reached, the last generated address will be returned. The reason for this is to allow for wallets to be automatically recovered from the 12 words seed, so it is kind of important. In order to generate a new address, you need to receive at least one transaction in any of the previous 20 addresses. I don't think the 100BTC you mention are related to this. Could you please provide more info for what you are trying to achieve? Thanks.

**Comment by isocolsky** [comment]
if you are invoking the `createAddress()` fn, try passing `ignoreMaxGap=true` to generate addresses beyond the limit.

**Comment by flujodedinero** [comment]
Ivan . yes, we are doing that what you say:

if you are invoking the createAddress() fn, try passing ignoreMaxGap=true to
generate addresses beyond the limit.

and the issue persists

Im fully opened to work on this

Thanks you for your help



2017-04-13 8:23 GMT-05:00 Ivan Socolsky <notifications@github.com>:

**Comment by isocolsky** [comment]
Just to understand better, when you receive a tx on one of the previous 100 addresses, do you start getting new addresses again?

**Comment by matiu** [comment]
fixed offline.
